NDefines.NReligion.MAX_CHURCH_POWER = 300
NDefines.NReligion.AUTHORITY_FROM_DEVELOPMENT = 0.04
NDefines.NDiplomacy.AE_HRE_INTERNAL = 0.05
NDefines.NDiplomacy.DIPLOMATIC_ACTION_FABRICATE_CLAIM_HRE_FACTOR = 1.25
NDefines.NReligion.YEARLY_HARMONIZATION_PROGRESS = 0.1
NDefines.NAI.PEACE_TERMS_PROVINCE_HRE_UNJUSTIFIED_MULT = 1
NDefines.NAI.MISSIONARY_MAINTENANCE_SHARE = 0.25